'use client';

import LegalLayout from '@/components/user/LegalLayout';

export default function DataPage() {
  return (
    <LegalLayout title="Data Terms" lastUpdated="August 2026">
      <div style={{ fontFamily: "'Inter', sans-serif" }}>
        <p style={{ marginBottom: 16 }}>
          These Data Terms (&quot;Terms&quot;) govern the collection, use, processing, storage, and deletion of data on the ONCHYRA platform (&quot;Platform&quot;). By using the Platform, you agree to the data practices described herein. These Terms should be read in conjunction with our Privacy Policy.
        </p>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>1. Data Ownership</h3>
        <p style={{ marginBottom: 12 }}>
          ONCHYRA respects your rights over your personal data. We affirm the following ownership principles:
        </p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}><strong>Your Data, Your Rights:</strong> You retain full ownership of all personal information you provide to the Platform. We do not claim ownership over your personal data, account information, or transaction history.</li>
          <li style={{ marginBottom: 6 }}><strong>License Grant:</strong> By providing data to the Platform, you grant ONCHYRA a limited, non-exclusive, revocable license to process your data solely for the purposes of providing and improving the Platform and its services.</li>
          <li style={{ marginBottom: 6 }}><strong>Aggregated Data:</strong> ONCHYRA may collect, use, and share aggregated, de-identified data derived from your use of the Platform. This data cannot reasonably be used to identify you and is not subject to the ownership provisions of these Terms.</li>
          <li style={{ marginBottom: 6 }}><strong>Platform Data:</strong> ONCHYRA retains ownership of all data generated by the Platform itself, including analytics data, performance metrics, and system logs that do not contain personally identifiable information.</li>
        </ul>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>2. Data Collection</h3>
        <p style={{ marginBottom: 12 }}>We collect data from and about you in the following ways:</p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}><strong>Information You Provide:</strong> Account registration details, transaction information, support communications, and any other data you voluntarily submit through the Platform.</li>
          <li style={{ marginBottom: 6 }}><strong>Automatically Collected Data:</strong> Device information (hardware model, operating system, unique device identifiers), IP address, browser type, geolocation data (with your permission), usage patterns, and interaction data collected through cookies and similar technologies.</li>
          <li style={{ marginBottom: 6 }}><strong>Third-Party Sources:</strong> We may receive data from third-party services, including payment processors and publicly available databases used for compliance purposes.</li>
          <li style={{ marginBottom: 6 }}><strong>Blockchain Data:</strong> Transaction records and wallet addresses associated with your account are recorded on public blockchain networks and are inherently transparent and immutable.</li>
        </ul>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>3. Data Processing</h3>
        <p style={{ marginBottom: 12 }}>
          ONCHYRA processes your data in accordance with the following principles and purposes:
        </p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}><strong>Service Delivery:</strong> To operate, maintain, and provide the Platform and its features, including account management, transaction processing, mining reward calculations, and referral tracking.</li>
          <li style={{ marginBottom: 6 }}><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, legal processes, or enforceable governmental requests, including anti-money laundering (AML) and counter-terrorism financing (CTF) obligations.</li>
          <li style={{ marginBottom: 6 }}><strong>Security:</strong> To detect, prevent, and address fraud, unauthorized access, and other harmful activities that may threaten the Platform or its users.</li>
          <li style={{ marginBottom: 6 }}><strong>Improvement:</strong> To analyze usage patterns, conduct research, develop new features, and improve the Platform&apos;s performance, reliability, and user experience.</li>
          <li><p><strong>Communication:</strong> To send you service-related notices, account alerts, promotional communications (with your consent), and respond to your inquiries and support requests.</p></li>
        </ul>
        <p style={{ marginBottom: 12 }}>
          All data processing activities are conducted in accordance with applicable data protection laws, including the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and other relevant legislation.
        </p>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>4. Data Retention</h3>
        <p style={{ marginBottom: 12 }}>
          We retain your personal data only for as long as necessary to fulfill the purposes for which it was collected, including to satisfy any legal, regulatory, accounting, or reporting requirements.
        </p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}><strong>Account Data:</strong> Retained for the duration of your account and for up to seven (7) years after account closure to comply with financial record-keeping regulations.</li>
          <li style={{ marginBottom: 6 }}><strong>Transaction Data:</strong> Retained for a minimum of seven (7) years from the date of the transaction in compliance with anti-money laundering regulations.</li>
          <li style={{ marginBottom: 6 }}><strong>Communication Records:</strong> Customer support communications are retained for three (3) years from the date of the last communication.</li>
          <li><p><strong>Usage Data:</strong> Aggregated and anonymized usage data may be retained indefinitely for analytics purposes. Identifiable usage data is retained for two (2) years from the date of collection.</p></li>
        </ul>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>5. Data Deletion</h3>
        <p style={{ marginBottom: 12 }}>
          You have the right to request the deletion of your personal data, subject to certain legal exceptions:
        </p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}><strong>Account Deletion:</strong> You may request account deletion through your account settings or by contacting support. Upon deletion, your personal data will be removed from active systems within thirty (30) days.</li>
          <li style={{ marginBottom: 6 }}><strong>Legal Exceptions:</strong> We may retain certain data where required by law, for legitimate business purposes (such as fraud prevention), or to resolve disputes. You will be informed of any data retained after an account deletion request.</li>
          <li style={{ marginBottom: 6 }}><strong>Backup Deletion:</strong> Data may persist in our backup systems for up to ninety (90) days after deletion from active systems. During this period, the data is not actively processed or used.</li>
          <li><p><strong>Deletion Confirmation:</strong> Upon completion of the deletion process, you will receive a confirmation through the platform. Certain anonymized data derived from your original data may be retained in aggregated form.</p></li>
        </ul>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>6. Cross-Border Data Transfers</h3>
        <p style={{ marginBottom: 12 }}>
          Your data may be transferred to and processed in countries other than your country of residence. These countries may have data protection laws that differ from the laws of your jurisdiction.
        </p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}><strong>Transfer Mechanisms:</strong> For transfers from the European Economic Area (EEA), United Kingdom, or Switzerland, we use Standard Contractual Clauses (SCCs) approved by the European Commission or rely on adequacy decisions where available.</li>
          <li style={{ marginBottom: 6 }}><strong>Data Centers:</strong> Our primary data centers are located in the United States (AWS us-east-1, us-west-2) and the European Union (AWS eu-west-1). We ensure that our cloud providers maintain appropriate security certifications, including SOC 2 Type II, ISO 27001, and PCI DSS.</li>
          <li><p><strong>Safeguards:</strong> We implement appropriate technical and organizational safeguards for cross-border transfers, including encryption, access controls, and regular security assessments of our service providers.</p></li>
        </ul>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>7. Data Security Measures</h3>
        <p style={{ marginBottom: 12 }}>
          We employ comprehensive security measures to protect your data against unauthorized access, alteration, disclosure, or destruction:
        </p>
        <ul style={{ marginBottom: 16, paddingLeft: 20 }}>
          <li style={{ marginBottom: 6 }}>End-to-end encryption for sensitive data transmission</li>
          <li style={{ marginBottom: 6 }}>Hardware security modules (HSMs) for cryptographic key management</li>
          <li style={{ marginBottom: 6 }}>Regular vulnerability assessments and penetration testing</li>
          <li style={{ marginBottom: 6 }}>Employee background checks and security awareness training</li>
          <li><p>Incident response procedures with 72-hour breach notification</p></li>
        </ul>

        <h3 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.8)', marginBottom: 10, marginTop: 20 }}>8. Contact Us</h3>
        <p style={{ marginBottom: 12 }}>For questions about these Data Terms or to exercise your data rights, please contact us through the platform&apos;s support section.</p>
      </div>
    </LegalLayout>
  );
}
